version: '3'

services:
  
  cde-bootstrap:
    env_file:
      - ".env"
    build:
      tags:
        - "${IMG_NAME}_vscde-bootstrap:${IMG_TAG}"
        - "${IMG_NAME}_vscde-bootstrap:${IMG_VER}"
      labels:
        version: "$IMG_VER"
        description: "[BOOTSTRAP] $IMG_DESC"
        base-image: "$BASE_IMG_NAME:$BASE_IMG_TAG"
      context: ./
      dockerfile: "$HOST_DOCKERFILES_DIR/vscde-bootstrap"
      network: host
      args:
        # Base
        BASE_IMG_NAME:            "$BASE_IMG_NAME"
        BASE_IMG_TAG:             "$BASE_IMG_TAG"
        # User
        CONT_USER:                "$BOOT_CONT_USER"
        CONT_USER_UID:            "$BOOT_CONT_USER_UID"
        CONT_USER_GROUPS:         "$BOOT_CONT_USER_GROUPS"
        # Host directories
        HOST_SCRIPTS_DIR:         "$HOST_SCRIPTS_DIR"
        # SSH
        HOST_SSH_KEYPAIR_NAME:    "$HOST_SSH_KEYPAIR_NAME"
        # Container directories
        CONT_CDE_DIR:             "$CONT_CDE_DIR"
    stdin_open: true
    tty: true
    userns_mode: "$CONT_USERNS_MODE"
    stop_grace_period: 0s
    restart: "no"
    network_mode: "none"
    volumes:
      - type: bind
        source: "$HOST_CDE_DIR"
        target: "$CONT_CDE_DIR"

  cde:
    env_file:
      - ".env"
    build:
      tags:
        - "${IMG_NAME}_vscde:${IMG_TAG}"
        - "${IMG_NAME}_vscde:${IMG_VER}"
      labels:
        version: "$IMG_VER"
        description: "$IMG_DESC"
        base-image: "$BASE_IMG_NAME:$BASE_IMG_TAG"
      context: ./
      dockerfile: "$HOST_DOCKERFILES_DIR/vscde-default"
      network: host
      args:
        BASE_IMG_NAME:               "$BASE_IMG_NAME"
        BASE_IMG_TAG:                "$BASE_IMG_TAG"
        CONT_USER:                   "$CONT_USER"
        CONT_USER_GROUPS:            "$CONT_USER_GROUPS"
        CONT_USER_UID:               "$CONT_USER_UID"
        HOST_SCRIPTS_DIR:            "$HOST_SCRIPTS_DIR"
        HOST_CONFIGS_DIR:            "$HOST_CONFIGS_DIR"
        HOST_USERS_PASS_DIR:         "$HOST_USERS_PASS_DIR"
        HOST_CODIUM_EXTS_DIR:        "$HOST_CODIUM_EXTS_DIR"
        HOST_SSH_DIR:                "$HOST_SSH_DIR"
        CONT_PROJ_DIR:               "$CONT_PROJ_DIR"
        CONT_CDE_DIR:                "$CONT_CDE_DIR"
        HOST_SSH_KEYPAIR_NAME:       "$HOST_SSH_KEYPAIR_NAME"
        CONT_PKGS:                   "$CONT_PKGS"
        HOST_CACHE_DIR:              "$HOST_CACHE_DIR"
        CONT_CODIUM_EXTS:            "$CONT_CODIUM_EXTS"
        CONT_GIT_CONFIG_INHERITANCE: "$CONT_GIT_CONFIG_INHERITANCE"
    tty: true
    stdin_open: false
    userns_mode: "$CONT_USERNS_MODE"
    stop_grace_period: 0s
    restart: "no"
    networks:
      - "cde-net"
    ports:
      - "$CONT_IP:$CONT_SSH_PORT:2022"
    volumes:
      - type: bind
        source: "$HOST_PROJ_DIR"
        target: "$CONT_PROJ_DIR"

networks:
  cde-net:
    driver: bridge
    internal: false
